### PR TITLE
Add support for transit passes

### PR DESCRIPTION
**Pull request by htwyford**
Transit pass fields have different names than GO fields and must be supported separately. Also, all transit pass-related transactions print a balance of $0.00 and the tool breaks if either the first or last entries in the CSV have a balance of zero.

Here are two CSVs for testing. One has my real data for November (with the sensitive fields cleared) that has a combination of transit and balance-based transactions. The second CSV removes all the balance transactions to simulate someone who uses Presto on the TTC exclusively.

[test-data.zip](https://github.com/kvark/presto-stats/files/3906300/test-data.zip)

This is the first thing I've written in Rust — sorry if the style is unconventional!

### CODE REVIEW

**Comment by kvark** [comment]
Thank you for the PR!
If sounds like we filter out some of the classes entirely:
  - "Fare Inspection"
  - "Transit Pass Payment"

Would you mind doing it in the original collection, e.g.:
```rust
let records: Vec<Record> = rdr
        .deserialize()
        .map(Result::unwrap)
        .filter(|r| r.class != "Fare Inspection" && r.class != "Transit Pass Payment")
        .collect();
```

**Comment by pakenhams** [comment]
Keeping “Transit Pass Payment” allows the tool to print the number of times you used your MetroPass in a month, which I think is a fun/useful stat. Are you amenable to keeping it?

**Comment by htwyford** [comment]
Keeping “Transit Pass Payment” allows the tool to print the number of times you used your MetroPass in a month, which I think is a fun/useful stat. Are you amenable to keeping it?

**Comment by kvark** [comment]
Ok, let's proceed, and I'll see if I can clean it up a bit as a follow up.

**Pull request merged**
